In [355]:
import pandas as pd
import numpy as np

# 5.1 Introduction to pandas Data Structures

### Series

In [356]:
obj = pd.Series([4, 7, -5, 3])

In [357]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

And so on...

In [358]:
obj.values

array([ 4,  7, -5,  3])

In [359]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [360]:
obj2 = pd.Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])

In [361]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [362]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [363]:
obj2['a']

-5

In [364]:
obj2['d'] = 6

In [365]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [366]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [367]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [368]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [369]:
'b' in obj2

True

In [370]:
'e' in obj2

False

In [371]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [372]:
obj3 = pd.Series(sdata)

In [373]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [374]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [375]:
obj4 = pd.Series(sdata, index = states)

In [376]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [377]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [378]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [379]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [380]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [381]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [382]:
obj4.name = 'population'

In [383]:
obj4.index.name = 'state'

In [384]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [385]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [386]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [387]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

In [388]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
      'year': [2000, 2001, 2002, 2001, 2002, 2003],
      'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [389]:
frame = pd.DataFrame(data)

In [390]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [391]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [392]:
pd.DataFrame(data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [393]:
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'],
                      index = ['one', 'two', 'three', 'four',
                               'five', 'six'])

In [394]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [395]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [396]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [397]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [398]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [399]:
frame2['debt'] = 16.5

In [400]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [401]:
frame2['debt'] = np.arange(6.)

In [402]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [403]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])

In [404]:
frame2['debt'] = val

In [405]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [406]:
frame2['eastern'] = frame2.state == 'Ohio'

In [407]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [408]:
del frame2['eastern']

In [409]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [410]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [411]:
frame3 = pd.DataFrame(pop)

In [412]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [413]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [414]:
pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [415]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [416]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [417]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [418]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [419]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [420]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [421]:
obj = pd.Series(range(3), index = ['a', 'b', 'c'])

In [422]:
index = obj.index

In [423]:
index

Index(['a', 'b', 'c'], dtype='object')

In [424]:
index[1:]

Index(['b', 'c'], dtype='object')

In [425]:
labels = pd.Index(np.arange(3))

In [426]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [427]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)

In [428]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [429]:
obj2.index is labels

True

In [430]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [431]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [432]:
'Ohio' in frame3.columns

True

In [433]:
2003 in frame3.index

False

In [434]:
dup_labels = pd.Index (['foo', 'foo', 'bar', 'bar'])

In [435]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# 5.2 Essential Functionality

### Reindexing

In [436]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])

In [437]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [438]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [439]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [440]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])

In [441]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [442]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [443]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index = ['a', 'c', 'd'],
                     columns = ['Ohio', 'Texas', 'California'])

In [444]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [445]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [446]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [447]:
states = ['Texas', 'Utah', 'California']

In [448]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [449]:
#frame.loc[['a', 'b', 'c', 'd'], states]  #doesn't work, text may be inaccurate or missing step

### Dropping Entries from An Axis

In [450]:
obj = pd.Series(np.arange(5.), index = ['a', 'b', 'c', 'd', 'e'])

In [451]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [452]:
new_obj = obj.drop('c')

In [453]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [454]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [455]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns = ['one', 'two', 'three', 'four'])

In [456]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [457]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [458]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [459]:
data.drop(['two', 'four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [460]:
obj.drop('c', inplace = True)

In [461]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Indexing, Selection, and Filtering

In [462]:
obj = pd.Series(np.arange(4.), index = ['a', 'b', 'c', 'd'])

In [463]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [464]:
obj['b']

1.0

In [465]:
obj[1]

1.0

In [466]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [467]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [468]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [469]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [470]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [471]:
obj['b':'c'] = 5

In [472]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [473]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns = ['one', 'two', 'three', 'four'])

In [474]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [475]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [476]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [477]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [478]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [479]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [480]:
data[data < 5] = 0

In [481]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection with loc and iloc

In [482]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [483]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [484]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [485]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [486]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [487]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### Integer Indexes

In [488]:
ser = pd.Series(np.arange(3.))

In [489]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [490]:
ser2 = pd.Series(np.arange(3.), index = ['a', 'b', 'c'])

In [491]:
ser2[-1]

2.0

In [492]:
ser[:1]

0    0.0
dtype: float64

In [493]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [494]:
ser.iloc[:1]

0    0.0
dtype: float64

### Arithmetic and Data Alignment

In [495]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])

In [496]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index = ['a', 'c', 'e', 'f', 'g'])

In [497]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [498]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [499]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [500]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns = list('bcd'),
                   index = ['Ohio', 'Texas', 'Colorado'])

In [501]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns = list('bde'),
                   index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [502]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [503]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [504]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [505]:
df1 = pd.DataFrame({'A': [1, 2]})

In [506]:
df2 = pd.DataFrame({'B': [3, 4]})

In [507]:
df1

A
0  1
1  2

In [508]:
df2

B
0  3
1  4

In [509]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [510]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns = list('abcd'))

In [511]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns = list('abcde'))

In [512]:
df2.loc[1, 'b'] = np.nan

In [513]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [514]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [515]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [516]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [517]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [518]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [519]:
df1.reindex(columns = df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### Operations between DataFrame and Series

In [520]:
arr = np.arange(12.).reshape((3, 4))

In [521]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [522]:
arr[0]

array([0., 1., 2., 3.])

In [523]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [524]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     columns = list('bde'),
                     index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [525]:
series = frame.iloc[0]

In [526]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [527]:
series

b    0
d    1
e    2
Name: Utah, dtype: int64

In [528]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [529]:
series2 = pd.Series(range(3), index = ['b', 'e', 'f'])

In [530]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [531]:
series3 = frame['d']

In [532]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [533]:
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int64

In [534]:
frame.sub(series3, axis = 'index')

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

### Function Application and Mapping

In [535]:
frame = pd.DataFrame(np.random.randn(4, 3), columns = list('bde'),
                     index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [536]:
frame

b         d         e
Utah    1.481325  0.946458  0.545345
Ohio   -0.162073 -0.403449  0.089866
Texas  -0.603873 -1.498671  0.018264
Oregon -0.860179 -0.151762  0.519808

In [537]:
np.abs(frame)

b         d         e
Utah    1.481325  0.946458  0.545345
Ohio    0.162073  0.403449  0.089866
Texas   0.603873  1.498671  0.018264
Oregon  0.860179  0.151762  0.519808

In [538]:
f = lambda x : x.max() - x.min()

In [539]:
frame.apply(f)

b    2.341503
d    2.445129
e    0.527081
dtype: float64

In [540]:
frame.apply(f, axis = 'columns')

Utah      0.935980
Ohio      0.493316
Texas     1.516935
Oregon    1.379987
dtype: float64

In [541]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])

In [542]:
frame.apply(f)

b         d         e
min -0.860179 -1.498671  0.018264
max  1.481325  0.946458  0.545345

In [543]:
format = lambda x : '%.2f' % x

In [544]:
frame.applymap(format)

b      d     e
Utah     1.48   0.95  0.55
Ohio    -0.16  -0.40  0.09
Texas   -0.60  -1.50  0.02
Oregon  -0.86  -0.15  0.52

In [545]:
frame['e'].map(format)

Utah      0.55
Ohio      0.09
Texas     0.02
Oregon    0.52
Name: e, dtype: object

### Sorting and Ranking

In [546]:
obj = pd.Series(range(4), index = ['d', 'a', 'b', 'c'])

In [547]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [548]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index = ['three', 'one'],
                     columns = ['d', 'a', 'b', 'c'])

In [549]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [550]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [551]:
frame.sort_index(axis = 1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [552]:
obj = pd.Series([4, 7, -3, 2])

In [553]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [554]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [555]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [556]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [557]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [558]:
frame.sort_values(by = 'b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [559]:
frame.sort_values(by = ['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [560]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [561]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [562]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [563]:
obj.rank(ascending = False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [564]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})

In [565]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [566]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis Indexes with Duplicate Labels

In [567]:
obj = pd.Series(range(5), index = ['a', 'a', 'b', 'b', 'c'])

In [568]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [569]:
obj.index.is_unique

False

In [570]:
obj['a']

a    0
a    1
dtype: int64

In [571]:
obj['c']

4

In [572]:
df = pd.DataFrame(np.random.randn(4, 3), index = ['a', 'a', 'b', 'b'])

In [573]:
df

0         1         2
a  0.085743  2.115083 -2.431657
a  1.040400  0.616626 -1.411830
b -0.659533 -0.134750 -0.633158
b  0.206496 -0.218844 -2.207120

In [574]:
df.loc['b']

0         1         2
b -0.659533 -0.134750 -0.633158
b  0.206496 -0.218844 -2.207120

# 5.3 Summarizing and Computing Descriptive Statistics

In [575]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index = ['a', 'b', 'c', 'd'],
                  columns = ['one', 'two'])

In [576]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [577]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [578]:
df.sum(axis = 'columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [579]:
df.mean(axis = 'columns', skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [580]:
df.idxmax()

one    b
two    d
dtype: object

In [581]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [582]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [583]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [584]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance

In [585]:
import pandas_datareader.data as web

In [586]:
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [587]:
price = pd.DataFrame({ticker: data['Adj Close']
                      for ticker, data in all_data.items()})

In [588]:
volume = pd.DataFrame({ticker: data['Volume']
                       for ticker, data in all_data.items()})

In [589]:
returns = price.pct_change()

In [590]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2022-04-04  0.023693  0.000922  0.017937  0.020913
2022-04-05 -0.018942 -0.010593 -0.012985 -0.017958
2022-04-06 -0.018451  0.003879 -0.036606 -0.027555
2022-04-07  0.001804 -0.006492  0.006244 -0.005183
2022-04-08 -0.011793 -0.004317 -0.012045 -0.008368

In [591]:
returns['MSFT'].corr(returns['IBM'])

0.480375555790982

In [592]:
returns['MSFT'].cov(returns['IBM'])

0.00014402710763456193

In [593]:
returns.MSFT.corr(returns.IBM)

0.480375555790982

In [594]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.429236  0.746572  0.668194
IBM   0.429236  1.000000  0.480376  0.455280
MSFT  0.746572  0.480376  1.000000  0.786989
GOOG  0.668194  0.455280  0.786989  1.000000

In [595]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000382  0.000141  0.000261  0.000230
IBM   0.000141  0.000281  0.000144  0.000135
MSFT  0.000261  0.000144  0.000320  0.000249
GOOG  0.000230  0.000135  0.000249  0.000312

In [596]:
returns.corrwith(returns.IBM)

AAPL    0.429236
IBM     1.000000
MSFT    0.480376
GOOG    0.455280
dtype: float64

In [597]:
returns.corrwith(volume)

AAPL   -0.081417
IBM    -0.128674
MSFT   -0.068788
GOOG   -0.089850
dtype: float64

### Unique Values, Value Counts, and Membership

In [598]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [599]:
uniques = obj.unique()

In [600]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [601]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [602]:
pd.value_counts(obj.values, sort = False)

a    3
c    3
d    1
b    2
dtype: int64

In [603]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [604]:
mask = obj.isin(['b', 'c'])

In [605]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [606]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [607]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [608]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [609]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [610]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})

In [611]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [612]:
result = data.apply(pd.value_counts).fillna(0)

In [613]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0